apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resume-screening-service.fullname" . }}-secret
  labels:
    {{- include "resume-screening-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  PINECONE_API_KEY: {{ .Values.secrets.pineconeApiKey | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | quote }}
